[project]
name = "dcbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py>=2.6.2",
    "pre-commit>=4.3.0",
    "python-dotenv[cli]>=1.1.1",
    "ruff>=0.12.11",
]
